// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvyomxwvtzpxyggtwmim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2eW9teHd2dHpweHlnZ3R3bWltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MTA4MDUsImV4cCI6MjA2ODQ4NjgwNX0.-jQPu4anVJxSLstkmLi8J3orRyul1Gcc8e9eaox8QN8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});